Update Desert.hpp
2bnb/2bnb-factions pull request #46
Opened 2024-05-14 06:02 UTC by tmthwoods

Fixed non-arsenal equipment

2024-05-21 19:22 UTC, metformin21 commented
faction files are @Amateur-God's repertoire so I'm not too familiar, I'm willing to merge this after skimming it though if he isn't going to look

2024-05-21 19:33 UTC, Amateur-God commented
Will have a look when I'm at my PC maybe tomorrow if that's okay @tmthwoods

2024-05-22 14:35 UTC, Amateur-God commented on addons/UK_2BNB/infantry/Desert.hpp
@tmthwoods are we no longer using the 3CB smokeshells?

2024-05-22 14:35 UTC, Amateur-God commented on addons/UK_2BNB/infantry/Desert.hpp
or any 3CB GL rounds?

2024-05-22 14:35 UTC, Amateur-God commented on addons/UK_2BNB/weapons/index.hpp
did i put the ; by mistake when i wrote this originally?

2024-06-17 15:47 UTC, Amateur-God requested changes
Didnt update index,hpp to include winter

2024-06-17 17:00 UTC, Amateur-God commented on addons/UK_2BNB/infantry/Desert.hpp
> -    respawnLinkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","UK3CB_BAF_Soflam_Laserdesignator","UK3CB_BAF_H_Mk6_DDPM_C","UK3CB_BAF_V_Osprey_DDPM3","UK3CB_BAF_G_Tactical_Bl
Deleted the " at the end of DDPM3 on respawn linked items breaking the quotes

2024-06-17 17:00 UTC, Amateur-God commented on addons/UK_2BNB/infantry/Desert.hpp
> -    respawnLinkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","UK3CB_BAF_Soflam_Laserdesignator","UK3CB_BAF_H_Mk6_DDPM_C","UK3CB_BAF_V_Osprey_DDPM3","UK3CB_BAF_G_Tactical_Bl
needs replacing so arma can read it properly

2024-06-17 17:02 UTC, Amateur-God requested changes
add " back into respawnLinkedItems

2024-06-21 17:40 UTC, Amateur-God approved these changes

2024-06-21 17:41 UTC, merged